version: '3.5'

volumes:
  postgres_data:
    external:
      true

services:
  nginx:
    container_name: test_nginx
    image: nginx:latest
    depends_on:
      - backend
    links:
      - backend
    volumes:
      - ${PWD}/compose/nginx/test.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/static:/static
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host

  backend:
    container_name: test_backend
    image: test_backend
    build:
        context: .
        dockerfile: ${PWD}/compose/backend/Dockerfile
    env_file:
      - compose/backend/backend.env
      - compose/postgres/postgres.env
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ${PWD}/static:/static
    command: /start


  postgres:
    image: postgres:10.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./compose/postgres/postgres.env
    expose:
      - "5432"


  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - 8080:8080