#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


echo "Apply database migrations"
python backend/manage.py migrate --noinput

if [ ! -z "$FIXTURES_DIR" ]; then
    echo "Apply fixtures"
    find ${FIXTURES_DIR} -type f -iname "*.json" -exec python backend/manage.py loaddata "{}" \;
fi

echo "Generating static"
python backend/manage.py collectstatic --noinput

/usr/local/bin/gunicorn settings.wsgi --bind 0.0.0.0:8000 --chdir=/apps/backend
